### ISSUE TITLE
Need error handling when connect attempt fails.

### ISSUE THREAD

**Issue by Niteblade** [Exeu/apai-io#60]
Recommend to re-attempt to connect after a few seconds of delay when first attempt was not successful.

[11-Jan-2015 09:27:55 GMT] PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/Request/Soap/Request.php:152

**Comment by Exeu** [comment]
Sorry but this does not belong to the library. It should be more on the application side instead here.

**Comment by Niteblade** [comment]
So what you're saying is that it's up to me to write some kind of error handling procedure for your code?

[16-Jan-2015 12:51:44 GMT] PHP Fatal error:  Uncaught SoapFault exception: [aws:Server.InternalError] We encountered an internal error. Please try again. in /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/Request/Soap/Request.php:152
Stack trace:
#0 /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/Request/Soap/Request.php(152): SoapClient->__soapCall('BrowseNodeLooku...', Array)
#1 /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/Request/Soap/Request.php(67): ApaiIO\Request\Soap\Request->performSoapRequest(Object(ApaiIO\Operations\BrowseNodeLookup), Array)
#2 /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/ApaiIO.php(73): ApaiIO\Request\Soap\Request->perform(Object(ApaiIO\Operations\BrowseNodeLookup))
#3 /home/***/public_html/***/_amazonNodes/config.php(81): ApaiIO\ApaiIO->runOperation(Object(ApaiIO\Operations\BrowseNodeLookup))
#4 /home/***/public_html/***/_amazonNodes/03_UpdateChildNodes.php(59): _BrowseAmazon('12306')
#5 /home/***/public_html/***/_amazonNodes/03_ in /home/***/public_html/__Apai-IO/vendor/exeu/apai-io/lib/ApaiIO/Request/Soap/Request.php on line 152

**Comment by Exeu** [comment]
no you write a error handling procedure which covers your problems, which both caused by Aws and/or some connection problems of your server ;)

**Comment by Niteblade** [comment]
Just wanted to share this in case anyone else has the same issue.

I changed from SOAP to REST.
I edited the "Rest" Request.php file and added (Somewhere around line 162):

```php
if (false == $result)  {	
$limit = 0;
while((curl_errno($ch) == 7 or curl_errno($ch) == 28 or $limit = 0) and $limit < 6)
    {
        sleep (5);
        $result = curl_exec($ch);
        $limit++;
    }
}
```

I will include more of the surrounding code so that others will be able to find where to add it easily:

```php
		$curlError = false;
		$errorNumber = null;
		$errorMessage = null;
		
		$result = curl_exec($ch);
		
		/* Added */
		if (false == $result) {	
			$limit = 0;
			while((curl_errno($ch) == 7 or curl_errno($ch) == 28 or $limit = 0) and $limit < 6)
			{
				sleep (5);
				$result = curl_exec($ch);
				$limit++;
			}
		}
		/* End of Added */

		if (false === $result) {
			$curlError = true;
			$errorNumber = curl_errno($ch);
			$errorMessage = curl_error($ch);
		}
			
		curl_close($ch);

**Comment by cyrgit** [comment]
Having the error handling inside the API library itself is easier than having to implement it at the application level.

I would prefer for this code to be more parametric, allowing the number of retries to be determined, either by configuration or by function call parameter. As well, the use of a known Exception type would be ideal, so the application can be coded to handle the permanent fail condition, rather than a simple retry.

The fact is, that any application which needs to connect to the Amazon API will at some point encounter these exceptions. I've even seen it happen on AWS EC2 machines, which have a very good uptime and are part of Amazon's own infrastructure. We should think of this as an expected scenario rather than an odd edge case.

That being the case, it would be nicer for retry to be part of the library itself. Why have everyone reinvent the wheel, when a standard implementation for needed code can be provided?
